spring:
  application:
    name: service-file
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
server:
  port: 8002

file:
  upload:
    file-root-path: /Users/huangwenxuan/test
    image-path: /image
    video-path: /video
