server:
  port: 8009
spring:
  application:
    name: service-acl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB
#    converters:
#      preferred-json-mapper: gson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:common-mysql.yml
      - optional:nacos:common-redis.yml
      - optional:nacos:common-jwt.yml
mybatis-plus:
  mapper-locations: classpath:com/venson/aclservice/mapper/xml/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    path: /var/logs/changliulab
  level:
    root: info
