spring:
  application:
    name: service-oss
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:service-oss-dev.yaml
