spring:
  application:
    name: service-edu
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:common-mysql.yaml
      - optional:nacos:common-jwt.yml
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
  mapper-locations: classpath:com/venson/eduservice/mapper/xml/*.xml
server:
  port: 8001
logging:
  file:
    path: /var/logs/changliulab
  level:
    root: info
