server:
  port: 8004
spring:
  application:
    name: service-cms
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/changliulab?serverTimezone=GMT%2B8
    username: root
    password: 123
  jackson:
    date-format: YYYY-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 18000000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
  mapper-locations: classpath:com/venson/educms/mapper/xml/*.xml
