server:
  port: 8001
spring:
  application:
    name: service-edu
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/changliulab?serverTimezone=GMT%2B8
    username: root
    password: 123
  jackson:
    date-format: YYYY-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
#logging:
#  config: c
#  level:
#    root: info
